# Generated by Django 3.2.3 on 2021-05-15 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_publisher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('year', models.IntegerField()),
                ('number_of_page', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshelf.author')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshelf.publisher')),
            ],
        ),
    ]
