# Generated by Django 3.2.3 on 2021-05-15 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0003_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='number_of_page',
        ),
    ]
